#!/usr/bin/env bash
set -euo pipefail
source terraform.tfvars
terraform destroy
aws ec2 delete-key-pair --key-name $key_name --region $region
rm -rf .terraform* terraform.tfstate* tf_output \
   $key_name.pem config_files __pycache__
if command -v tmux >/dev/null && tmux has-session -t rondb_bench; then
  tmux kill-session -t rondb_bench
fi
