#!/usr/bin/env bash
set -euo pipefail
source terraform.tfvars
aws ec2 create-key-pair --key-name $key_name --key-type ed25519 --region $region --output text > $key_name.pem
chmod 600 $key_name.pem
sed -ri 's/^.*\s(-+BEGIN)/\1/;s/(KEY-+)\s.*$/\1/;' $key_name.pem
