#!/usr/bin/env bash
set -euo pipefail
source terraform.tfvars
aws ec2 create-key-pair \
    --key-name $key_name \
    --key-type ed25519 \
    --region $region \
    --query KeyMaterial \
    --output text \
    > $key_name.pem
chmod 600 $key_name.pem
